# Generated by Django 5.2.7 on 2025-10-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="avatars/",
                verbose_name="用户头像",
            ),
        ),
    ]
