# Generated by Django 5.2.7 on 2025-11-20 09:41

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uid",
            field=models.CharField(
                default=apps.users.models.generate_uid,
                editable=False,
                max_length=12,
                unique=True,
                verbose_name="用户UID",
            ),
        ),
    ]
