# Generated by Django 5.2.7 on 2025-11-23 08:45

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="支持格式: JPG, PNG, GIF, WEBP，最大10MB",
                null=True,
                upload_to=apps.users.models.user_avatar_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
                verbose_name="用户头像",
            ),
        ),
    ]
