# Generated by Django 5.2.7 on 2025-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="reasoning_content",
            field=models.TextField(
                blank=True,
                help_text="DeepSeek Reasoner 模型的思考过程",
                null=True,
                verbose_name="推理过程",
            ),
        ),
    ]
