# Generated by Django 5.2.7 on 2025-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_reasoning_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="chat_files/%Y/%m/",
                verbose_name="上传文件",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="parsed_content",
            field=models.TextField(blank=True, null=True, verbose_name="文件解析内容"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="消息内容"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "纯文本"),
                    ("markdown", "Markdown"),
                    ("image_url", "图片链接"),
                    ("file", "文件上传"),
                ],
                default="text",
                max_length=20,
                verbose_name="内容类型",
            ),
        ),
    ]
