# Generated by Django 5.2.7 on 2025-11-25 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatmessage_file_chatmessage_parsed_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="chat_files/%Y/%m/", verbose_name="文件"
                    ),
                ),
                (
                    "parsed_content",
                    models.TextField(blank=True, null=True, verbose_name="解析内容"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="chat.chatmessage",
                        verbose_name="所属消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息附件",
                "verbose_name_plural": "消息附件",
            },
        ),
    ]
