# Generated by Django 5.2.7 on 2025-11-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_messagefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "已完成"),
                    ("generating", "生成中"),
                    ("interrupted", "已中断"),
                    ("error", "错误"),
                ],
                default="completed",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
